import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import Header from "@/components/Header/Header";
import { Providers } from "./provider/Providers";
import { Suspense } from "react";
import Loading from "@/components/Loading/Loading";

const inter = Vazirmatn({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={inter.className}>
        <Providers>
          <NextUIProvider>
            <Header />
            <div className="w-9/12 mx-auto mt-4">
              {children}
            </div>
          </NextUIProvider>
        </Providers>
      </body>
    </html>
  );
}
